{% set name = "solarforecastarbiter" %}
{% set version = "1.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/solarforecastarbiter-{{ version }}.tar.gz
  sha256: 35a5d2fe8128f0415816d6fdabdeda3dec6f0a63c02507c50962bcf36f51b389

build:
  number: 0
  noarch: python
  entry_points:
    - solararbiter=solarforecastarbiter.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - aiohttp
    - bokeh >=1.4.0, <2
    - click
    - jsonschema
    - loky
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas >=0.25.1
    - plotly >=4.5.0, <5
    - psutil
    - pvlib-python ==0.8.0
    - python >=3.7
    - requests <=2.25.1
    - scipy
    - sentry-sdk
    - statsmodels
    - pytables
    - xarray

test:
  imports:
    - solarforecastarbiter
    - solarforecastarbiter.io
  commands:
    - pip check
    - solararbiter --help
  requires:
    - pip

about:
  home: https://github.com/solararbiter/solarforecastarbiter-core
  summary: Core framework for Solar Forecast Arbiter
  dev_url: https://github.com/solararbiter/solarforecastarbiter-core
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wholmgren
    - lboeman
